FROM ubuntu:latest
ARG REDISHOST
ARG REDISPORT
ARG PORT
ENV REDISHOST $REDISHOST
ENV REDISPORT $REDISPORT
ENV PORT $PORT
EXPOSE $REDISHOST
EXPOSE $REDISPORT
EXPOSE $PORT
COPY ./sub_api /sub_api
RUN chmod +x /sub_api
RUN /sub_api


